### ISSUE TITLE
v4.3 Release ToDo List

### ISSUE THREAD

**Issue by Franky47** [FortySevenEffects/arduino_midi_library#55]
## Code changes
- [x] Update `keywords.txt` with API changes.
- [x] Fix warnings
- [x] Write unit tests for Callbacks.
- [x] Write complete unit tests for Thru
## Release Workflow
- [x] Build all examples on all boards
- [x] Write release notes
- [x] Update readme
- [x] Generate documentation
- [x] Package release
- [x] Tag revision
- [x] Upload to GitHub releases
- [x] Upload documentation
- [x] Update Arduino page (does it even still exist ?)
- [x] Contact Arduino team for official addition to the library manager
- [x] Check update on PlatformIO
- [x] Close milestone
